spring:
  application:
    name: product-service
  config:
    import: optional:file:./.config/application.yml
  datasource:
    url: ${DB-URL}
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

app:
  api:
    version: @project.version@
    title: Product Service API
    description: A toy RESTful Product Web Service built with Kotlin, Spring Boot, and Gradle
  security:
    user: ${APP_USERNAME}
    password: ${APP_PASSWORD}
